# Generated by Django 4.2.15 on 2025-09-23 13:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("accounts", "0001_initial"),
    ]

    operations = [
        migrations.RenameField(
            model_name="bankaccount",
            old_name="verification_note",
            new_name="verification_notes",
        ),
    ]
